FROM node:23.2.0
WORKDIR /app

COPY package*.json ./
RUN npm install --force
COPY . .
ARG PORT
ARG NODE_ENV
ARG MONGODB_URI
ARG REDIS_URL
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG JWT_SECRET
ARG JWT_EXPIRE
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_PRIVATE_KEY
ARG FIREBASE_CLIENT_EMAIL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASS
ARG STRIPE_SECRET_KEY
ARG STRIPE_PUBLISHABLE_KEY
ARG MAX_FILE_SIZE
ARG UPLOAD_PATH
ARG ALLOWED_ORIGINS
ARG RATE_LIMIT_WINDOW_MS   
ARG RATE_LIMIT_MAX_REQUESTS 
ARG FIREBASE_STORAGE_BUCKET

ENV PORT=$PORT
ENV NODE_ENV=$NODE_ENV
ENV MONGODB_URI=$MONGODB_URI
ENV REDIS_URL=$REDIS_URL
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRE=$JWT_EXPIRE
ENV FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
ENV FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY
ENV FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASS=$SMTP_PASS
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
ENV MAX_FILE_SIZE=$MAX_FILE_SIZE
ENV UPLOAD_PATH=$UPLOAD_PATH
ENV ALLOWED_ORIGINS=$ALLOWED_ORIGINS
ENV RATE_LIMIT_WINDOW_MS=$RATE_LIMIT_WINDOW_MS
ENV RATE_LIMIT_MAX_REQUESTS=$RATE_LIMIT_MAX_REQUESTS
ENV FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
EXPOSE 8080
CMD ["node", "server.js"]
ENV NODE_ENV=production